# Generated by Django 5.2.7 on 2025-10-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrestAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apprehension_state', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('apprehension_aor', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('apprehension_criminality', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('age_category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('citizenship_country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('month', models.DateField(blank=True, db_index=True, null=True)),
                ('total_arrests', models.IntegerField(default=0)),
                ('convicted_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('other_immigration_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'arrest_aggregation',
                'ordering': ['-month', 'apprehension_state'],
                'indexes': [models.Index(fields=['month'], name='arrest_aggr_month_ad8db7_idx'), models.Index(fields=['apprehension_state', 'month'], name='arrest_aggr_apprehe_fc25e3_idx'), models.Index(fields=['apprehension_aor', 'month'], name='arrest_aggr_apprehe_ee70cd_idx'), models.Index(fields=['citizenship_country', 'month'], name='arrest_aggr_citizen_dd8efc_idx'), models.Index(fields=['gender', 'month'], name='arrest_aggr_gender_5dc81b_idx'), models.Index(fields=['age_category', 'month'], name='arrest_aggr_age_cat_44bc4b_idx'), models.Index(fields=['apprehension_criminality', 'month'], name='arrest_aggr_apprehe_ce3bc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArrestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apprehension_date', models.DateField(blank=True, db_index=True, null=True)),
                ('apprehension_state', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('apprehension_aor', models.CharField(blank=True, max_length=100, null=True)),
                ('apprehension_criminality', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('citizenship_country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('unique_identifier', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('age_category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'arrest_record',
                'ordering': ['-apprehension_date', 'apprehension_state'],
                'indexes': [models.Index(fields=['apprehension_state', 'apprehension_date'], name='arrest_reco_apprehe_0f5716_idx'), models.Index(fields=['age_category', 'apprehension_date'], name='arrest_reco_age_cat_d0aaae_idx'), models.Index(fields=['gender', 'apprehension_date'], name='arrest_reco_gender_170567_idx'), models.Index(fields=['citizenship_country', 'apprehension_date'], name='arrest_reco_citizen_51b237_idx'), models.Index(fields=['apprehension_criminality', 'apprehension_date'], name='arrest_reco_apprehe_f637bb_idx'), models.Index(fields=['apprehension_state', 'age_category', 'apprehension_date'], name='arrest_reco_apprehe_92c393_idx'), models.Index(fields=['apprehension_state', 'gender', 'apprehension_date'], name='arrest_reco_apprehe_dd7b40_idx'), models.Index(fields=['apprehension_state', 'citizenship_country', 'apprehension_date'], name='arrest_reco_apprehe_5a0705_idx'), models.Index(fields=['age_category', 'gender', 'apprehension_date'], name='arrest_reco_age_cat_1c5fee_idx'), models.Index(fields=['age_category', 'citizenship_country', 'apprehension_date'], name='arrest_reco_age_cat_7ba98d_idx'), models.Index(fields=['apprehension_state'], name='arrest_reco_apprehe_41a0ea_idx'), models.Index(fields=['age_category'], name='arrest_reco_age_cat_a96707_idx'), models.Index(fields=['apprehension_date'], name='arrest_reco_apprehe_8c226d_idx')],
            },
        ),
    ]
