# Generated by Django 5.2.7 on 2025-10-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_arrestaggregation_arrestrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrestaggregation',
            name='pending_count',
        ),
        migrations.AddField(
            model_name='arrestaggregation',
            name='pending_charges_count',
            field=models.IntegerField(default=0),
        ),
    ]
