# Generated by Django 5.2.7 on 2025-10-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_remove_arrestaggregation_pending_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrestMonthlyChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apprehension_state', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('month', models.DateField(blank=True, db_index=True, null=True)),
                ('gender', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('apprehension_criminality', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('citizenship_country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('age_category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'arrest_monthly_chart',
            },
        ),
    ]
