# Generated by Django 5.2.7 on 2025-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_arrestmonthlychart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AORHeatMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apprehension_state', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('apprehension_aor', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('month', models.DateField(blank=True, db_index=True, null=True)),
                ('citizenship_country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('age_category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('total', models.IntegerField(default=0)),
                ('percent_of_total', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'aor_heat_map',
            },
        ),
    ]
