# Generated by Django 5.2.7 on 2025-11-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_aorheatmap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArrestAggregation',
        ),
        migrations.DeleteModel(
            name='demoModel',
        ),
    ]
